Images by tag
AppFolioOnboarding/image-sharer-joshuasbates pull request #18
Opened 2018-02-15 22:47 UTC by joshuasbates

Closes #8

2018-02-16 04:45 UTC, shiboying commented
And also I think we can make the commit history cleaner. I think for this story, basically the following steps: 
1) add the gem
2) create the ImagesForTagName service and add unit test for this service
3) add to index action in the images_controller and add tests
4) display tags in `show.html.erb` and `index.html.erb`, add flow tests if you have one.

It is a good practice to do one commit with code together with the corresponding tests. And make the commit history organized is easier to review and understand the code for future reference.

2018-02-16 04:45 UTC, shiboying requested changes

2018-02-16 04:45 UTC, shiboying commented on db/migrate/20180212230128_acts_as_taggable_on_migration.acts_as_taggable_on_engine.rb
> +  def self.up
Just a note (since this is from `acts_as_taggable_on`, `self` is not necessary in migrations.

2018-02-16 04:45 UTC, shiboying commented on app/views/images/new.html.erb
>      <%= f.input :imageurl, as: :url, label: "Image URL" %>
I think `imageurl` should be named as `image_url`

2018-02-16 04:45 UTC, shiboying commented on app/views/images/new.html.erb
> +    <%= f.input :tag_list, as: :string, label: "Tags" %>
We use single quote in APM for string.

2018-02-16 04:45 UTC, shiboying commented on app/views/images/show.html.erb
> +    <p><strong>Tags: </strong>
Minor, but prefer `<strong>Tags: </strong>` on a separate line make it more structured

2018-02-16 04:45 UTC, shiboying commented on app/views/images/index.html.erb
> +  <% ActsAsTaggableOn::Tag.all.map(&:name).each do |tag| %>
First I think you could do `ActsAsTaggableOn::Tag.all.map(&:name).join(' ')`. And second I think this is to display all tags that exists right? I think this story is to display each image's tags below each image on the index page. So I think you should add this part below line 10 and use `@image.tag_list`.

2018-02-16 04:45 UTC, shiboying commented on app/services/images_for_tag_name.rb
> +    image_list
Here the prefered way is:
```Ruby
image_list = if tag_name.nil?
                Image.order(created_at: :desc)
             else
                Image.tagged_with(tag_name).order(created_at: :desc)
             end
```

2018-02-16 04:45 UTC, shiboying commented on app/views/images/index.html.erb
> +    <%= link_to(tag_name, "?tag_name=#{tag_name}") %>
You can use this `images_path(tag_name: tag_name)` for the path.

2018-02-16 04:45 UTC, shiboying commented on app/views/images/index.html.erb
> +    <% if @images %>
If I remember correctly, if no image with such tag the `@images` will return `[]` So you don't need to do this check.

2018-02-16 04:45 UTC, shiboying commented on Gemfile
> +gem 'acts-as-taggable-on', '~> 5.0'
As your first commit is to add this gem, if this is just to use a newer version, you should fixup this change to the first commit.

2018-02-16 04:45 UTC, shiboying commented on test/controllers/images_controller_test.rb
> +  def test_should_create_image
👍

2018-02-16 04:45 UTC, shiboying commented on app/services/images_for_tag_name.rb
> +    image_list = if tag_name.nil?
We usually don't prefer a commit for fix code styles. We will fixup to the commit which this belongs to.

2018-02-17 00:38 UTC, joshuasbates commented
@shiboying , after rebasing to master after merging our recently-approved "image-tag" branch, you should find the file list more targeted to this issue.  That being said, we will also clean up the Git history to be more succinct.

2018-02-20 18:01 UTC, shiboying approved these changes

2018-02-20 18:20 UTC, shiboying approved these changes

2018-02-20 18:20 UTC, shiboying approved these changes
👍

2018-02-20 18:24 UTC, merged